name: Quibble

on:
  - push
  - pull_request

jobs:
  quibble:
    env:
      MEDIAWIKI_VERSION: master
      DOCKER_REGISTRY: docker-registry.wikimedia.org
      DOCKER_IMAGE: releng/quibble-stretch-php73

      # includes deps of deps
      # @todo auto generate below by inspecting https://raw.githubusercontent.com/wikimedia/integration-config/master/zuul/parameter_functions.py
      DEPENDENCIES: >-
        mediawiki/extensions/BetaFeatures
        mediawiki/extensions/Echo
        mediawiki/extensions/CentralAuth
        mediawiki/extensions/EventLogging
        mediawiki/extensions/EventStreamConfig

    strategy:
      matrix:
        stage:
          - phpunit-unit
          - phpunit
          - phpunit-standalone
          - npm-test
          - composer-test
          # - qunit
          # - selenium
          # - api-testing

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up
        run: |
          # Get the latest docker tag (Ref: https://github.com/thcipriani/dockerregistry)
          echo "DOCKER_LATEST_TAG=$(curl -sL "https://${DOCKER_REGISTRY}/v2/${DOCKER_IMAGE}/tags/list" |
            python3 -c 'import json;print("\n".join(json.loads(input())["tags"]))' |
            grep -v latest | sort -Vr | head -1)" >> $GITHUB_ENV

          # Used by actions/cache
          echo $DEPENDENCIES > .dependencies

          # Make directories
          mkdir -p /home/runner/quibble
          cd /home/runner/quibble
          mkdir -p cache log
          chmod 777 cache log

      - name: Cache Quibble
        uses: actions/cache@v2
        with:
          path: /home/runner/quibble/docker-image
          key: '${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_LATEST_TAG }}'
      - name: Load or pull Quibble
        run: |
          docker load -i /home/runner/quibble/docker-image || \
            docker pull "${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${DOCKER_LATEST_TAG}"

      - name: Cache MediaWiki installation
        uses: actions/cache@v2
        id: cache
        with:
          path: /home/runner/quibble/src
          key: "${{ runner.os }}-${{ env.MEDIAWIKI_VERSION }}-${{ hashFiles('.dependencies') }}"

      - name: Download MediaWiki and extensions
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          cd /home/runner/quibble
          git clone -b "${MEDIAWIKI_VERSION}" --depth 1 https://gerrit.wikimedia.org/r/mediawiki/core src
          git clone --recurse-submodules -b "${MEDIAWIKI_VERSION}" --depth 1 https://gerrit.wikimedia.org/r/mediawiki/skins/Vector src/skins/Vector
          for dep in $DEPENDENCIES; do
            git clone --recurse-submodules -b "${MEDIAWIKI_VERSION}" --depth 1 "https://gerrit.wikimedia.org/r/${dep}" src/"$(echo $dep | cut -d'/' -f2,3)"
          done

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: /home/runner/quibble/cache
          key: "${{ runner.os }}-${{ env.MEDIAWIKI_VERSION }}-${{ hashFiles('**/*.lock') }}"

      - name: Run Quibble
        run: |
          cd /home/runner/quibble
          # Move our extension
          sudo cp -r "${GITHUB_WORKSPACE}" src/extensions/
          chmod 777 src
          find src cache -mindepth 1 -exec sudo chown nobody:nogroup {} \;
          docker run \
            -e ZUUL_PROJECT=mediawiki/extensions/"${{ github.event.repository.name }}" \
            -v "$(pwd)"/cache:/cache \
            -v "$(pwd)"/log:/workspace/log \
            -v "$(pwd)"/src:/workspace/src \
            "${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${DOCKER_LATEST_TAG}" \
            --skip-zuul \
            --packages-source composer \
            --run "${{ matrix.stage }}" \
            $DEPENDENCIES

      - name: Tear down
        run: |
          cd /home/runner/quibble
          # See https://doc.wikimedia.org/quibble/index.html#remove-localsettings-php-between-runs
          rm "$(pwd)"/src/LocalSettings.php
          docker save -o "$(pwd)"/docker-image "${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${DOCKER_LATEST_TAG}"
